<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a>
            </div>
            <div class="panel-body">
                <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal" method="post">
                  <div class="form-group">
                      <label class="control-label col-sm-3" for="name">Nome: </label>
                      <div class="col-sm-8">
                          <input required type="text" name="name" class="form-control" id="name" placeholder="Nome Completo" value="<?php echo $this->request->post('name') ?>">
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="control-label col-sm-3" for="email">Email:</label>
                      <div class="col-sm-8">
                          <input required type="email" name="email" class="form-control" id="email" placeholder="seuemail@site.com.br">
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="control-label col-sm-3" for="username">Usuário:</label>
                      <div class="col-sm-8">
                          <input required type="text" name="username" class="form-control" id="username" placeholder="Usuário">
                      </div>
                  </div>
                  <div class="form-group">
                      <label class="control-label col-sm-3" for="password">Senha:</label>
                      <div class="col-sm-8">
                          <input required type="password" name="password" class="form-control" id="password" placeholder="Senha">
                      </div>
                  </div>

                  <div class="form-group">
                  <div class="col-sm-offset-3 col-sm-10">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
</div>
